### PR TITLE
proposed performance improvement

### PR DESCRIPTION
**Pull request by fametrano**
using pow should provide performance improvement similar to native library, the code is terser, behaviour is strictly equivalent according to my tests

### CODE REVIEW

**Comment by richardkiss** [comment]
Fermat's little theorem! Very clever! This depends on m being prime, which is not a requirement of ```inverse_mod``, so to do this properly, I'd say we just remove the ```inverse_mod``` function and move this clever trick into the places that call it. Would do you think?

**Comment by fametrano** [comment]
My understanding is that inverse_mod might be never used in pycoin with a non-prime m. Anyway inlining it everywhere might decrease code readability and puzzle bitcoin devs looking for a reference implementation of inverse_mod. I do leave the decision to your judgement.

**Comment by richardkiss** [comment]
I like the idea, but I ran a test and using ```pow``` actually seems to be slower. Did you test this at all, and if so, did you get a different result?

```
import time
from pycoin.ecdsa.numbertheory import inverse_mod

a,m = (0x1ffffffffffffebaaedce6af48a03bbfd25e8cd0364141, 0xfffffffffffffffffffffffffffffffffffffffffffffffffffffffefffffc2f)

def test(f):
    now = time.time()
    for i in range(10000):
        d = f(a, m)
    return time.time() - now

def im2(a, m):
    return pow(a, m-2, m)

print(test(inverse_mod))
print(test(im2))
```

**Comment by fametrano** [comment]
sorry my bad. I assumed that native pow would have been faster, it is not the case.
Sorry for wasting your time, hope at least you had as much fun with Fermat little theorem as I had

**Pull request closed without merging**
