### PR TITLE
READY FOR REVIEW - Alternate to PR #92 - Add `Tx.who_signed_me` convenience method to reveal which address(es) were...

### PR DESCRIPTION
**Pull request by posita**
...responsible for signing a particular transaction. This can be useful for seeing who signed an m-of-n multisig where m < n.

I'm not sure that adding a method to `Tx` is the right approach. It may be that `pycoin.tx.tx_utils` is a better place for this. Either way, I was unable to find an API or service out there that told me, for example, which two keys were used to sign a 2-of-3 `MULTISIG`, so I made this and felt like contributing. :smiley:

### CODE REVIEW

**Comment by shayanb** [comment]
This actually is a useful tool, I guess we need lots of contribution on the multisig functionality for pycoin.

I resolved some issues on testnet multisig, but still couldn't resolve the partially sign transaction issues.

**Comment by mbogosian** [comment]
> This actually is a useful tool, I guess we need lots of contribution on the multisig functionality for pycoin.

In fairness, everybody does. The only reason I wrote this because I needed the functionality, and I couldn't find it elsewhere (this included looking at the blockchain.info and blockr.io APIs, but I might not have read through their docs carefully enough).

**Comment by mbogosian** [comment]
I just created #92 as an alternate approach. #92 provides the same functionality as the function `pycoin.tx_utils.who_signed_tx` instead of as the method `pycoin.tx.Tx.who_signed_me` in this version. Only one of #91 and #92 should be accepted and the other should be rejected.

**Comment by richardkiss** [comment]
I prefer #92 so I will close this.

**Pull request closed without merging**
