### PR TITLE
Don't try to parse too many signatures for P2SH scriptSig

### PR DESCRIPTION
**Pull request by devrandom**
In case we have a redeem script at end.

### CODE REVIEW

**Comment by devrandom** [comment]
Cc @tomholub

**Comment by sserrano44** [comment]
@richardkiss have you seen this PR?

**Comment by tomholub** [comment]
Works in my local environment. Yay! Less duct-taping outside the library. I'll deploy this in our dev environments to confirm.

**Comment by richardkiss** [comment]
Does anyone have a test case that failed before that passes now? That'd be great for regression testing.

**Comment by tomholub** [comment]
@richardkiss I cherry-picked the fix and added a test case in #145

**Comment by richardkiss** [comment]
Merged in #145

**Pull request closed without merging**
