### PR TITLE
Add Groestlcoin Support

### PR DESCRIPTION
**Pull request by Kefkius**
Add Groestlcoin support. This new PR is based on #314 feedback.

The Groestlcoin changes are almost completely contained within a `coins.groestlcoin` package, except for a new argument when creating a bitcoinish network which allows specifying the UI class. The most unwieldy change is in `network.parse`, which could benefit from becoming a class so that our changes could be implemented via inheritance (like the UI class).

There is still one issue due to the `groestlcoin_hash` dependency: In the previous PR, we discussed raising an ImportError when `groestlHash` is called. I've implemented this change. However, if the user passes a GRS address to ku without specifying the network, it will just output "can't parse" since it can't know that it *would* be able to parse the input if `groestlcoin_hash` were installed. Since I can't think of any way to solve that aside from complicating how ku parses input, it may have to stay that way.

### CODE REVIEW

**Comment by gruve-p** [comment]
@richardkiss This PR uses https://github.com/richardkiss/pycoin/tree/feature/parser as basis.
Can we get your input/feedback and try to get GRS finally in?

**Comment by richardkiss** [comment]
Apologies for the delay, I've been away from wifi for a couple weeks, will take a look now.

**Comment by richardkiss** [comment]
I did a `flake8 pycoin/coins/groestlcoin/parse.py` and got quite a few issues which suggests either some of this code is dead or there are hidden bugs.

```
pycoin/coins/groestlcoin/parse.py:5:1: F401 'pycoin.ui.Parser.parse_b58_double_sha256' imported but unused
pycoin/coins/groestlcoin/parse.py:9:1: E302 expected 2 blank lines, found 1
pycoin/coins/groestlcoin/parse.py:22:1: C901 'set_grs_parse' is too complex (71)
pycoin/coins/groestlcoin/parse.py:53:33: F821 undefined name 'h2b'
pycoin/coins/groestlcoin/parse.py:65:20: F821 undefined name 'h2b'
pycoin/coins/groestlcoin/parse.py:72:20: F821 undefined name 'b2h'
pycoin/coins/groestlcoin/parse.py:176:19: F821 undefined name 'h2b'
pycoin/coins/groestlcoin/parse.py:177:27: F821 undefined name 'sec_to_public_pair'
pycoin/coins/groestlcoin/parse.py:178:29: F821 undefined name 'is_sec_compressed'
pycoin/coins/groestlcoin/parse.py:260:5: E265 block comment should start with '# '
pycoin/coins/groestlcoin/parse.py:261:5: E265 block comment should start with '# '
```

**Comment by richardkiss** [comment]
Also, I've worked on `bitcoinish.py` more while I was offline, and refactored the `make_parser` which unfortunately also has broken some more of your code. I just now refactored out `ParserAPI.py` (and some other APIs) which has simplified things a bit.

**Comment by richardkiss** [comment]
Take a look at https://github.com/richardkiss/pycoin/tree/feature/grs which you should be able to merge with your branch. I'd also like if you could run `flake8` checks on your code in `pycoin/coins/groestlcoin` as there are some potential bugs and style issues:

```SolutionChecker.py:8:1: F401 'pycoin.satoshi.flags.VERIFY_DISCOURAGE_UPGRADABLE_WITNESS_PROGRAM' imported but unused
SolutionChecker.py:8:1: F401 'pycoin.satoshi.flags.VERIFY_CLEANSTACK' imported but unused
SolutionChecker.py:8:1: F401 'pycoin.satoshi.flags.VERIFY_WITNESS' imported but unused
SolutionChecker.py:17:20: F821 undefined name 'ZERO32'
SolutionChecker.py:30:20: F821 undefined name 'ZERO32'
SolutionChecker.py:41:24: F821 undefined name 'ZERO32'
SolutionChecker.py:44:20: F821 undefined name 'ZERO32'
SolutionChecker.py:51:16: F821 undefined name 'from_bytes_32'
Solver.py:4:1: E302 expected 2 blank lines, found 1
Tx.py:7:1: F401 '.hash.groestlHash' imported but unused
Tx.py:11:1: E302 expected 2 blank lines, found 1
uiclass.py:6:1: E302 expected 2 blank lines, found 1
uiclass.py:9:1: E302 expected 2 blank lines, found 1
```

**Comment by Kefkius** [comment]
@richardkiss I was about to comment on the refactor to `make_parser`. It has messed up some things but your `feature/grs` branch API refactoring appears to be a great improvement re: flexibility. I also ran flake8 on the `groestlcoin` package and future commits won't have errors like you found, thanks!

As for tests, I will ensure that a missing `groestlcoin_hash` package doesn't cause tests to fail. I'll still leave `groestlcoin_hash` in tox.ini so that all Groestlcoin tests run as well, but that will mean the CI tests don't account for when `groestlcoin_hash` is not present.

**Comment by Kefkius** [comment]
@richardkiss This latest change basically makes GRS appear to not work when the dependency isn't present. It causes the tests to behave correctly, and generally shifts the concern to us making sure users know what to do if they want to use pycoin with GRS.

**Comment by gruve-p** [comment]
@richardkiss 
Can we get your input/feedback and try to get GRS finally in?

**Comment by richardkiss** [comment]
Merged to develop, d8eb95c7fd1b6d83ca38aab5091ffc3804ed6f63. It will make its way to master soon. Thanks for your patience on this.

**Pull request closed without merging**
