### PR TITLE
Sphinx setup

### PR DESCRIPTION
**Pull request by johnwlockwood**
Setup Sphinx and add rst source files for each module. With this, you can go to the repo Settings:Integration & services and add ReadTheDocs. Although I think the way to connect it is via https://readthedocs.org/dashboard/.

I fixed the usage of `__all__`: it is supposed to be a list of strings of the names of the modules vs the modules themselves.

I fixed a case where an unexpected docstring indent caused a failure to generate.

This is branched from `valid-recipe-module-names` so will be a smaller pr if that goes in.

### CODE REVIEW

**Comment by richardkiss** [comment]
Wow, this is great! I'd just started working on sphinx integration myself, but you're way ahead of me, thank you so much!

**Comment by richardkiss** [comment]
Merged a rebased version.

**Comment by richardkiss** [comment]
I realize this is just the beginnings of a template and that there is much work to be done on making the documentation usable and coherent. This definitely a goal of mine. Let me know if you'd be interested in helping out.

**Comment by johnwlockwood** [comment]
I forgot to say you can build the html version of the docs by, from the docs directory, run make html. then look in _build/html and open index.html.

-John

**Comment by richardkiss** [comment]
Oh yes, I'm aware... I've already linked these docs to http://pycoin.readthedocs.io/

**Comment by johnwlockwood** [comment]
Ok, but, yes it is a starting point. There is plenty of docstrings to add to the code that will improve the docs it automatically builds.

**Comment by richardkiss** [comment]
Yes, for sure. One of the tasks is to go through the docs & code together and produce docstrings that are more coherent in the context of the sphinx documentation, so they both look better in the documentation, and better explain what they actually do and when you might use them.

Other tasks: an introduction, an overview of the code, more recipes, and the command-line tools.

**Comment by johnwlockwood** [comment]
Let me make a recommendation for managing this project. Try [Zube.io](https://zube.io)
I'd like to get to know this project better and can help. After years, watching your talk at Python SF helped me understand some things about bitcoin that I had not been able to grasped before.

**Comment by richardkiss** [comment]
OK, I've imported the project into <https://zube.io/richardkiss/pycoin/w/workspace-1/kanban>. I don't have much experience with this sort of thing, so let me know what you think I should do to get started.

**Comment by johnwlockwood** [comment]
If you add me as a user on there, I could see it. Zube has a lot of features, not all you'll use, but I like it for tracking tickets and tasks among contributers.
          
            
            On Mar 23 2017, at 6:47 pm, Richard Kiss <notifications@github.com> wrote:
            
            
              OK, I've imported the project into https://zube.io/richardkiss/pycoin/w/workspace-1/kanban. I don't have much experience with this sort of thing, so let me know what you think I should do to get started.

**Comment by richardkiss** [comment]
I can't figure out how to add you to the pycoin project on zube.io. I've added you to the github project, and I'll see if that makes a difference after you accept.

**Pull request closed without merging**
