### PR TITLE
Not ready (do not merge) - Fix #93. Fail validation for out-of-order multisig signatures and try to (re)order signatures correctly when partially signing.

### LINKED ISSUE #93: Fixed in PR #94 - `is_signature_ok` returns `True` for MULTISIG even though signatures appear out-of-order
From https://bitcoin.org/en/developer-reference#term-op-checkmultisig:

> Because public keys are not checked again if they fail any signature comparison, signatures must be placed in the signature script using the same order as their corresponding public keys were placed in the pubkey script or redeem script. See the OP_CHECKMULTISIG warning below for more details.

Right now, `pycoin` behaves like this:

```python
# start with tx1 (not shown) which has one TxIn that consumes
# a 2-of-2 multisig with keys k1 and k2 (in that order)

# make a copy of tx1 for comparison
tx2.tx_from_hex(tx1.as_hex())
tx2.set_unspents(tx1.unspents)

# sign tx1 in one order
tx1.sign(k1)
tx1.sign(k2)

# sign tx2 in the reverse order
tx2.sign(k2)
tx2.sign(k1)

# check some stuff
assert tx1.is_signature_ok(0) # works
assert tx2.is_signature_ok(0) # works (should fail if the next assertion fails)
assert tx1.txs_in[0].script == tx2.txs_in[0].script # fails (should work if the previous assertion works)

# an inspection of tx2.txs_in[0].script will reveal that the
# order of the signatures is inverted from that of
# tx1.txs_in[0].script
```

Either the last two assertions should both fail, or both work, but only the first works right now (which is the bug).

### PR DESCRIPTION
**Pull request by posita**
*UPDATE: Assuming the test run times are acceptable, additional performance tuning can be done as a separate PR.*

This PR creates some new unit tests geared toward fixing #93 and proposes a fix for failing validation if signatures appear out of order per the Bitcoin specification. It also proposes augmenting `ScriptMultisig.solve` to attempt to (re)order signatures correctly when signing, which means the following should now be equivalent (and generate the same script):

```python
tx1.sign(k1)
tx1.sign(k2)
tx2.sign(k2)
tx2.sign(k1)
assert tx1.is_signature_ok(0) # works
assert tx2.is_signature_ok(0) # works, but...
assert tx1.txs_in[0].script == tx1.txs_in[0].script # ...also works
```

### CODE REVIEW

**Comment by mbogosian** [comment]
My latest check-in apparently increases unit tests time by 3-4x! :open_mouth: It was actually *longer* before I made the changes to cache dummy signatures (instead of creating them in every loop iteration).

I tried running `cProfile` on the tests, and here's what I found:

```
% python -c 'import pstats, sys ; p = pstats.Stats(sys.argv[1]) ; p.strip_dirs().sort_stats("cumulative").print_stats(20)' profile_results
Sun Mar  1 08:41:37 2015    profile_results

         299274613 function calls (299269747 primitive calls) in 433.831 seconds

   Ordered by: cumulative time
   List reduced from 698 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.002    0.002  433.832  433.832 multisig_order_test.py:4(<module>)
        1    0.000    0.000  433.221  433.221 runner.py:140(run)
        1    0.000    0.000  433.221  433.221 suite.py:69(__call__)
        1    0.000    0.000  433.221  433.221 suite.py:88(run)
        8    0.000    0.000  433.220   54.153 case.py:392(__call__)
        8    0.000    0.000  433.220   54.153 case.py:295(run)
12468/7816    3.751    0.000  430.893    0.055 ellipticcurve.py:106(__mul__)
     5576    0.014    0.000  430.426    0.077 ellipticcurve.py:137(__rmul__)
  1902301  313.324    0.000  399.891    0.000 numbertheory.py:2(inverse_mod)
      464    0.001    0.000  361.822    0.780 TxIn.py:79(verify)
      464    0.003    0.000  361.821    0.780 vm.py:187(verify_script)
      928    0.029    0.000  361.818    0.390 vm.py:52(eval_script)
      783    0.028    0.000  360.638    0.461 ecdsa.py:147(possible_public_pairs_for_signature)
  1422553   12.700    0.000  319.740    0.000 ellipticcurve.py:146(double)
      314    0.001    0.000  308.039    0.981 Tx.py:340(is_signature_ok)
       20    0.001    0.000  233.215   11.661 multisig_order_test.py:277(_screw_up_signature_order_then_fix_it)
     1303    0.025    0.000  202.322    0.155 ecdsa.py:127(verify)
       28    0.001    0.000  195.040    6.966 multisig_order_test.py:309(_sign_out_of_order)
      158    0.002    0.000  193.382    1.224 Tx.py:354(sign)
      150    0.002    0.000  125.081    0.834 Tx.py:202(sign_tx_in)
```

```
% python -c 'import pstats, sys ; p = pstats.Stats(sys.argv[1]) ; p.strip_dirs().sort_stats("tottime").print_stats(20)' profile_results
Sun Mar  1 08:41:37 2015    profile_results

         299274613 function calls (299269747 primitive calls) in 433.831 seconds

   Ordered by: internal time
   List reduced from 698 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  1902301  313.324    0.000  399.891    0.000 numbertheory.py:2(inverse_mod)
285482795   86.567    0.000   86.567    0.000 {divmod}
  1422553   12.700    0.000  319.740    0.000 ellipticcurve.py:146(double)
  1908172    6.225    0.000    6.225    0.000 ellipticcurve.py:54(contains_point)
   477482    4.203    0.000  107.575    0.000 ellipticcurve.py:82(__add__)
12468/7816    3.751    0.000  430.893    0.055 ellipticcurve.py:106(__mul__)
  1908170    3.023    0.000    9.265    0.000 ellipticcurve.py:63(__init__)
     8766    1.351    0.000    1.351    0.000 {pow}
  2389985    1.007    0.000    1.007    0.000 ellipticcurve.py:73(__eq__)
  1425581    0.371    0.000    0.371    0.000 ellipticcurve.py:48(a)
  1903063    0.371    0.000    0.371    0.000 ellipticcurve.py:45(p)
     5582    0.299    0.000    0.299    0.000 ellipticcurve.py:109(leftmost_bit)
     3190    0.071    0.000    0.084    0.000 encoding.py:58(to_long)
      928    0.029    0.000  361.818    0.390 vm.py:52(eval_script)
      783    0.028    0.000  360.638    0.461 ecdsa.py:147(possible_public_pairs_for_signature)
     1303    0.025    0.000  202.322    0.155 ecdsa.py:127(verify)
     2245    0.021    0.000    1.166    0.001 encoding.py:232(sec_to_public_pair)
    14607    0.018    0.000    0.020    0.000 tools.py:38(get_opcode)
   132037    0.017    0.000    0.017    0.000 {ord}
     7007    0.016    0.000    0.058    0.000 streamer.py:46(stream_struct)
```

**Comment by posita** [comment]
While they still take a while, with 27800a7, I was able to cut my run times for the `MULTISIG` tests down to almost half of what they were in 15dc0ab:

```sh
% time PYTHONPATH=. ./tests/multisig_order_test.py
........
----------------------------------------------------------------------
Ran 8 tests in 267.931s

OK
PYTHONPATH=. ./tests/multisig_order_test.py  268.19s user 0.20s system 99% cpu 4:28.43 total
% time PYTHONPATH=. ./tests/multisig_order_test.py
........
----------------------------------------------------------------------
Ran 8 tests in 138.657s

OK
PYTHONPATH=. ./tests/multisig_order_test.py  139.09s user 0.08s system 99% cpu 2:19.17 total
```

While far from scientific, compare also the TravisCI run times for [build #190 (for 15dc0ab)](https://travis-ci.org/richardkiss/pycoin/builds/53519583) vs. [build #194 (for 27800a7)](https://travis-ci.org/richardkiss/pycoin/builds/55448347). So things are a little more tolerable now. :grin:

**Comment by richardkiss** [comment]
First off, this is great work.

One reason this slows down validation is because we are calling ```ecda.verify``` much more often than we were calling ```ecdsa.possible_public_pairs_for_signature```. If we could go back to using ```possible_public_pairs_for_signature``` then this would be perfect.

**Comment by posita** [comment]
> One reason this slows down validation is because we are calling ecda.verify much more often than we were calling ecdsa.possible_public_pairs_for_signature. If we could go back to using possible_public_pairs_for_signature then this would be perfect.

It may be true that this implementation calls `ecdsa.verify` more often than the previous implementation called `ecdsa.possible_public_pairs_for_signature`, but I don't know if that necessarily translates to worse performance. Consider the following.

Here's the `cProfile` run for `tests/multisig_order_test.py` using `ecdsa.verify` (from fb071a1 which is basically 27800a7 merged with recent changes in the master branch):

```sh
% python -c 'import pstats, sys ; p = pstats.Stats(sys.argv[1]) ; p.strip_dirs().sort_stats("cumulative").print_stats(20)' profile_results.fb071a1
Fri Mar 27 22:26:16 2015    profile_results.fb071a1

         129232372 function calls (129229393 primitive calls) in 174.567 seconds

   Ordered by: internal time
   List reduced from 225 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
   820910  125.946    0.000  160.813    0.000 numbertheory.py:2(inverse_mod)
123144350   34.867    0.000   34.867    0.000 {divmod}
   613367    5.116    0.000  128.407    0.000 ellipticcurve.py:146(double)
   823712    2.467    0.000    2.467    0.000 ellipticcurve.py:54(contains_point)
   205965    1.651    0.000   43.251    0.000 ellipticcurve.py:82(__add__)
7358/4379    1.464    0.000  172.969    0.039 ellipticcurve.py:106(__mul__)
   823711    1.171    0.000    3.648    0.000 ellipticcurve.py:63(__init__)
     4200    0.643    0.000    0.643    0.000 {pow}
  1032655    0.354    0.000    0.354    0.000 ellipticcurve.py:73(__eq__)
   614767    0.164    0.000    0.164    0.000 ellipticcurve.py:48(a)
   820732    0.156    0.000    0.156    0.000 ellipticcurve.py:45(p)
     2979    0.122    0.000    0.122    0.000 ellipticcurve.py:109(leftmost_bit)
     2014    0.048    0.000    0.058    0.000 encoding.py:58(to_long)
      928    0.029    0.000  107.617    0.116 vm.py:54(eval_script)
     1400    0.024    0.000    0.733    0.001 encoding.py:232(sec_to_public_pair)
     1400    0.022    0.000  160.725    0.115 ecdsa.py:127(verify)
    12235    0.015    0.000    0.017    0.000 tools.py:39(get_opcode)
    91321    0.014    0.000    0.014    0.000 {ord}
     2456    0.013    0.000    0.023    0.000 der.py:66(remove_integer)
     4774    0.012    0.000    0.040    0.000 streamer.py:46(stream_struct)
```

Here's the `cProfile` run for `tests/multisig_order_test.py` using `ecdsa.possible_public_pairs_for_signature` (fb071a1 with 27800a7 reversed with `git diff 27800a7~1 27800a7 | patch -p1 -R`):

```sh
% python -c 'import pstats, sys ; p = pstats.Stats(sys.argv[1]) ; p.strip_dirs().sort_stats("cumulative").print_stats(20)' profile_results.fb071a1-27800a7
Fri Mar 27 22:34:55 2015    profile_results.fb071a1-27800a7

         232958674 function calls (232955013 primitive calls) in 314.279 seconds

   Ordered by: internal time
   List reduced from 253 to 20 due to restriction <20>

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
  1480849  228.482    0.000  290.377    0.000 numbertheory.py:2(inverse_mod)
222235787   61.895    0.000   61.895    0.000 {divmod}
  1107480    9.104    0.000  231.639    0.000 ellipticcurve.py:146(double)
  1485359    4.508    0.000    4.508    0.000 ellipticcurve.py:54(contains_point)
   371474    2.929    0.000   78.252    0.000 ellipticcurve.py:82(__add__)
9747/6086    2.606    0.000  312.377    0.051 ellipticcurve.py:106(__mul__)
  1485358    2.106    0.000    6.627    0.000 ellipticcurve.py:63(__init__)
     5091    0.756    0.000    0.756    0.000 {pow}
  1860175    0.655    0.000    0.655    0.000 ellipticcurve.py:73(__eq__)
  1109283    0.284    0.000    0.284    0.000 ellipticcurve.py:48(a)
  1480757    0.283    0.000    0.283    0.000 ellipticcurve.py:45(p)
     4345    0.220    0.000    0.220    0.000 ellipticcurve.py:109(leftmost_bit)
     1757    0.039    0.000    0.047    0.000 encoding.py:58(to_long)
      928    0.025    0.000  247.767    0.267 vm.py:54(eval_script)
      660    0.018    0.000  247.216    0.375 ecdsa.py:147(possible_public_pairs_for_signature)
     1057    0.017    0.000  152.011    0.144 ecdsa.py:127(verify)
        1    0.016    0.016  314.280  314.280 runner.py:140(run)
     1143    0.016    0.000    0.591    0.001 encoding.py:232(sec_to_public_pair)
    12235    0.014    0.000    0.016    0.000 tools.py:39(get_opcode)
     2456    0.013    0.000    0.021    0.000 der.py:66(remove_integer)
```

So yes, `ecdsa.verify` is (understandably) called more often from the `ecdsa.verify` implementation, but if you compare the execution times and each line of the profile stats up to `vm.eval_script`, using `ecdsa.verify` over `ecdsa.possible_public_pairs_for_signature` seems pretty compelling.

I have not done extensive profiling and adjustment, and I might have missed something.

**Comment by posita** [comment]
The TL;DR of my last comment is that profiling suggests that `ecdsa.possible_public_pairs_for_signature` is computationally (at least as implemented) significantly more intensive that `ecdsa.verify`. This is probably due in part to [`ecdsa.possible_public_pairs_for_signature` making (probably at least) two calls to `ecdsa.verify`](https://github.com/richardkiss/pycoin/blob/0017740e9b7d756ba2799f72619901863128ce34/pycoin/ecdsa/ecdsa.py#L173) (which would explain the near 2x improvement when replacing each call to `ecdsa.possible_public_pairs_for_signature` with a call to `ecdsa.verify`).

**Comment by posita** [comment]
@richardkiss, I think I understand your https://github.com/richardkiss/pycoin/pull/94#issuecomment-87109930 better now after reading [this](https://bitcointalk.org/index.php?topic=38903.msg476100#msg476100) (bitcointalk.org). Calling `ecdsa.possible_public_pairs_for_signature` might be the appropriate thing to do generally, but these tests' performance will suffer.

At the risk of introducing complexity, it's possible to implement two approaches:

* Where 2m < n, deduce the public keys from the signatures and then compare them (in order) to the public keys to find a sufficient number of matches;
* Where 2m >= n, walk through the signatures and public keys as [described in the Wiki](https://en.bitcoin.it/wiki/Script).

I have not looked into it in any detail, but perhaps there are some lower level routines we can borrow and experiment with from [vbuterin/pybitcointools](/vbuterin/pybitcointools)?

**Comment by posita** [comment]
This PR is partially obsoleted by 5baef12eca4e62f99f483a625bd64b41328cef72, d73bac154668679c03e793359a3dd6dec3246260, and af38dfcf800dc4d11cf491db964eba52df722b5c. My [tests](https://github.com/posita/pycoin/blob/multisig-order/tests/multisig_order_test.py) still have a 100% failure rate when run against `master` (f758ca62b13761c867491596ccdc45fb3bde0f07), but it's probably best to start fresh given the merge issues with competing implementations.

**Pull request closed without merging**
