### PR TITLE
Blockcypher added, chain.com removed, Blockr refactored

### PR DESCRIPTION
**Pull request by shayanb**
Added blockcypher get_balance, get_tx and spendable_for_address for both testnet and mainnet.
Removed chain.com, they stopped offering blockexplorer API recently

### CODE REVIEW

**Comment by shayanb** [comment]
an easy fast test would be:
```
import blockcypher
import blockr_io

print blockcypher.BlockCypherProvider(netcode="XTN").get_balance("2N16oE62ZjAPup985dFBQYAuy5zpDraH7Hk")
print blockcypher.BlockCypherProvider(netcode="XTN").spendables_for_address("2N16oE62ZjAPup985dFBQYAuy5zpDraH7Hk")
print blockcypher.BlockCypherProvider().get_tx("f854aebae95150b379cc1187d848d58225f3c4157fe992bcd166f58bd5063449")

print blockr_io.BlockrioProvider(netcode="XTN").spendables_for_address("2N16oE62ZjAPup985dFBQYAuy5zpDraH7Hk")
print blockr_io.BlockrioProvider().get_tx("60c1f1a3160042152114e2bba45600a5045711c3a8a458016248acec59653471")
```

**Comment by richardkiss** [comment]
I've merged into my PYCOIN_PROVIDERS branch.

**Comment by richardkiss** [comment]
It's a bit of a mess right now... I need to be more diligent with naming consistency.

**Comment by shayanb** [comment]
Let me know how I can be helpful here :)

**Comment by richardkiss** [comment]
Although I'm not done yet, feel free to look at my PYCOIN_PROVIDERS branch and give feedback.

**Comment by kylianz** [comment]
Can anyone help me understand blockcypher and how is use token is it my private key

**Comment by richardkiss** [comment]
This has been merged in. Thank you!

**Pull request closed without merging**
