### PR TITLE
Add bitcoin testnet provider testnet.blockchain.info

### PR DESCRIPTION
**Pull request by ruoshan**

### CODE REVIEW

**Comment by richardkiss** [comment]
Can you refactor blockchain_info.py instead of creating a new file that is almost the same?

**Comment by ruoshan** [comment]
done. please check again when you're free. thanks.

**Comment by richardkiss** [comment]
Much nicer. You don't actually even need to subclass, but instead simply set `api_domain` to the right thing based on `netcode`. Then you can set use `PYCOIN_XTN_PROVIDERS="blockchain.info"`. Give that a go and I'll merge. (I can do it myself if you prefer, just let me know.)

**Comment by ruoshan** [comment]
Clean to go. Thank you.

**Pull request merged**
