### PR TITLE
Added Support for segwit xpubs

### LINKED ISSUE #251: Support for segwit xprv/xpubs
This is introduced in [electrum 3.0](https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES). BIP32 version prefix is changed to indicated segwit type. http://docs.electrum.org/en/latest/seedphrase.html#list-of-reserved-numbers

Trezor is now generating segwit addresses using yprv/ypub

### PR DESCRIPTION
**Pull request by shivaenigma**
Fixes #251.  I am not sure if I correctly followed the library _architecture_, so code may not be very elegant. Feel free to suggest changes

Thanks

### CODE REVIEW

**Comment by knaperek** [comment]
Test failed due to external service malfunction. Could you please re-run the tests?

**Comment by shivaenigma** [comment]
@knaperek 
The tests are already failing (even without including this pull request). Could you please help how to fix ?

**Comment by knaperek** [comment]
Yes I saw some outages, it seems to work right now. @shivaenigma please close & reopen this PR (it will re-trigger Travis tests).

**Comment by blockonomics** [comment]
Its not showing me open to close the PR. If you have permissions feel free to close

**Comment by shivaenigma** [comment]
Sorry was logged in as wrong user. Closed

**Comment by knaperek** [comment]
Re-opened here: https://github.com/richardkiss/pycoin/pull/260

**Pull request closed without merging**
