### PR TITLE
READY: Chain.com PROVIDER added + minor bug fix

### PR DESCRIPTION
**Pull request by shayanb**
fixing https://github.com/richardkiss/pycoin/issues/85

### CODE REVIEW

**Comment by mbogosian** [comment]
:+1: Thanks @shayanb!

**Comment by shayanb** [comment]
@mbogosian I can't find where it is included, anyhow it wasn't intended to be included, that is just a test file I'm using for playing around the library.

**Comment by mbogosian** [comment]
@shayanb, sorry to beat a dead horse :horse:. This might expose my complete ignorance of how Git or GitHub work, but I was referring to commit 6da5b8a367dc6f587605ed313d0d393f9fe32210 (`fix BIP32 for testnet`) referenced after my https://github.com/richardkiss/pycoin/pull/86#issuecomment-75588012. It looks like that includes the modifications to `.gitignore` that I mentioned. If this is not the case, my apologies. I have precious little experience with cross-repository pull requests. :blush:

**Comment by richardkiss** [comment]
This pull request has a lot going on in it. Some of the fixes have already been applied. @shayanb I'm going to close this request... if there are any changes that you think you need that aren't yet merged, perhaps you can do them one branch and change at a time so the discussion can be more focussed.

**Comment by shayanb** [comment]
@richardkiss sure, Thanks.
I will send another PR for chain.com provider. not sure the rest of the changes would be applicable anymore.

**Pull request closed without merging**
