### PR TITLE
NEEDS REVIEW - For #112. Properly fail on exception raised during `eval_script` but...

### PR DESCRIPTION
**Pull request by posita**
...comment out now-failing tests (whose proper results were originally hidden by suppressing the exception).

I'm pretty sure this provides a necessary fix, but it causes some imported tests to fail (see this https://github.com/richardkiss/pycoin/issues/112#issuecomment-89798230). It's important to note that ***those tests were always failing***, but suppressing the exception gave the false impression that they were passing. This PR ***does not fix those tests*** (it comments them out). However, without this fix, `eval_script` may give the false impression that a transaction is valid when it's not.

As such, I'm recommending merging this, marking #112 as fixed~~, and then filing a separate issue to uncomment and fix the missing tests~~. *UPDATE: I have opened #114 to track the missing/failing tests.*

### CODE REVIEW

**Comment by posita** [comment]
FYI, this PR implements the fix identified in this https://github.com/richardkiss/pycoin/issues/112#issue-66374906 (i.e., it returns `False` after catching the exception). I'm wondering if we shouldn't allow the exception to bubble up? I haven't looked through the code enough to know how that might break things....

**Comment by posita** [comment]
Tests are failing due to #119. PR #120 provides a fix.

**Comment by posita** [comment]
Squashed and rebased to `master` (f758ca62b13761c867491596ccdc45fb3bde0f07).

**Comment by richardkiss** [comment]
Merged in df0e3d93

**Pull request closed without merging**
