### PR TITLE
Add r, s, and z signature details to tx utility

### PR DESCRIPTION
**Pull request by gurnec**
This PR adds a new tx.py command-line option `-s` / `--verbose-signature` which extracts the ECDSA 'r' and 's' values from each signature found in the scriptSig(s).

When used with the `-a` option, it also displays the calculated signature_hash() value, 'z'.

There aren't any unit tests (yet)—if anyone's aware of an alternate utility that could be used to validate the new output, it would certainly make sense to add some tests.

### CODE REVIEW

**Comment by richardkiss** [comment]
Great patch, thanks!

**Comment by shayanb** [comment]
How is it possible to get the z value from tx_hex? https://github.com/richardkiss/pycoin/blob/master/pycoin/scripts/tx.py#L110

**Comment by richardkiss** [comment]
Upgrade to master, then use ```tx -as <tx_hex>```

**Comment by richardkiss** [comment]
This was broken, but I've added a test case, so this should stay unbroken going forward.

**Pull request merged**
