### PR TITLE
Add message signing features as mixin on Key

### PR DESCRIPTION
**Pull request by peter-conalgo**
This code extends "Key" class with member functions to use the private key to sign a text message, or the public key to verify a message.

It can also sign using just the message hash (useful in special cases) and provides a number of helper functions to parse signed messages and simplify usage.

I consider this code stable and well tested.

### CODE REVIEW

**Comment by richardkiss** [comment]
This functionality is great, but I'd like to see it turned into a separate file with functions that accept a key as a parameter.

**Comment by peter-conalgo** [comment]
I would like to revise this PR and get it merged.

I'm happy to isolate and turn into non-member functions. Please propose a file name and location.

Thanks!

**Comment by peter-conalgo** [comment]
Please see https://github.com/richardkiss/pycoin/pull/172

**Comment by peter-conalgo** [comment]
This branch is obsolete (sorry) and I believe I've already addressed py3 support in the final version of this code... See: https://github.com/richardkiss/pycoin/pull/172

**Pull request closed without merging**
