### PR TITLE
New message signing feature (functional style, with py3 support)

### PR DESCRIPTION
**Pull request by peter-conalgo**
New message signing feature:
- sign text with your Bitcoin (or altcoin) private key.
- verify signatures on messages
- parse / encode a commonly-observed RFC2440-like wrapper for those messages.

### CODE REVIEW

**Comment by richardkiss** [comment]
Looks great!

**Comment by peter-conalgo** [comment]
Bump.

**Comment by richardkiss** [comment]
Sorry for the delay. I definitely see the value in this code, and I know you're eager to merge it, but there are a few issues, redundancies and inconsistencies with the rest of pycoin I'd like to address before making it "official". I wonder how you'd feel about moving it to pycoin/contrib/ (and creating a pycoin/contrib/__init__.py) and then I'd be happy to merge it in immediately.

**Comment by peter-conalgo** [comment]
I was really hoping we'd found a home for this code and an appropriate API. It's really self contained right now and feels pretty logical to me.

**Comment by richardkiss** [comment]
I made some minor changes and committed.

**Pull request merged**
