### PR TITLE
Added Support for segwit xpubs

### LINKED ISSUE #251: Support for segwit xprv/xpubs
This is introduced in [electrum 3.0](https://github.com/spesmilo/electrum/blob/master/RELEASE-NOTES). BIP32 version prefix is changed to indicated segwit type. http://docs.electrum.org/en/latest/seedphrase.html#list-of-reserved-numbers

Trezor is now generating segwit addresses using yprv/ypub

### PR DESCRIPTION
**Pull request by shivaenigma**
Fixes #251. I am not sure if I correctly followed the library architecture, so code may not be very elegant. Feel free to suggest changes

Thanks

### CODE REVIEW

**Comment by knaperek** [comment]
Tests passing now, great!

**Comment by shivaenigma** [comment]
@knaperek do you have permissions to do a merge ? Its seems @richardkiss  hasn't been active since Oct 22

**Comment by knaperek** [comment]
Unfortunately I don't. Let's wait a few days, he could be on a vacation still.

**Comment by shivaenigma** [comment]
Lets wait... if possible would be great if you can get admin permissions. There hasn't been any activity from @richardkiss on this from Oct

**Comment by richardkiss** [comment]
This is a fine idea, but I'm hesitant to merge because much of this stuff has changed a lot in the develop branch. In particular, there is a new notion of parsers that are network-specific, but it's not fully flushed out yet. I will get something like this in there (and thank you for doing the heavy lifting), but I just can't say when.

**Comment by blockonomics** [comment]
@richardkiss no problem, Let me know if you need any help ...Also I am concerned about https://github.com/richardkiss/pycoin/issues/254. Can produce some stats if necessary

**Comment by shivaenigma** [comment]
@richardkiss no problem, Let me know if you need any help ...Also I am concerned about #254. Can produce some stats if necessary

**Comment by reiven** [comment]
ping

**Comment by richardkiss** [comment]
I'm sorry I haven't been able to merge this yet. I'm reworking how network-specific parsers work, and I will keep this issue in mind.

**Comment by iteratelance** [comment]
Any updates on this thread as to when a new release might be published? I'm having a really difficult time discovering a python bitcoin library that supports BIP49 addresses.

**Comment by shivaenigma** [comment]
This is waiting on @richardkiss

**Comment by richardkiss** [comment]
The way parsing works has changed quite a bit since this patch was written. The bad news is that this patch will also have to be tweaked quite a bit to work with the new mechanism. The good news is that the solution will be much cleaner.

I apologize for having put this off for so long. I would like to offer whatever support I need to get this patch applied. Let me know how I can help.

**Comment by shivaenigma** [comment]
It will take time for me to understand the new parsing structure and redo this. @richardkiss if you have bandwith feel free to take it up yourself and close this (should be much faster)

**Comment by freenancial** [comment]
I'm going to take a shot and see if I can get this patch working.

**Comment by freenancial** [comment]
Got zpub parsing with some ugly draft code in my branch here:
https://github.com/freenancial/pycoin/commits/ypub-zpub-support

Once I finished polishing the code, I'll send out a new PR since it would be very different from this PR here due to the big change of how parsing works.

**Comment by fenidik** [comment]
Sad that we still don't have ypub support.

**Comment by blockonomics** [comment]
@richardkiss  an updates on this? Tested on master and zpub/ypub support is still missing

**Comment by richardkiss** [comment]
Unfortunately this patch was put together before the pycoin API had evolved enough to allow this sort of thing to be done in a reasonable way. The API now does have a reasonable place for this code to go, but the patch no longer works. It's probably just a few hours work re-integrating, but my day job has been very intense recently so I can't commit to a date on getting this done at this time.

**Comment by blockonomics** [comment]
Thanks @richardkiss . Feel free to close this. We can create a PR based on the new structure of code

**Comment by blockonomics** [comment]
Our team will take up redoing this PR based on the new code structure. You should be hearing shortly from us. Feel free to close this

**Comment by richardkiss** [comment]
> Could you add LTC segwit addresses (starting with M)?

This should be much easier to do now @fenidik... if you're still interested, I can help point you to what to do for a PR.

**Pull request closed without merging**
